[package]
name = "http-get"
version = "0.1.0"
authors = ["Remsko <pinoit.remi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.5.1"

