[package]
name = "json-macro"
version = "0.1.0"
authors = ["Remsko <pinoit.remi@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
